Add -Devise
Bantealem/rails-blog-app pull request #10
Opened 2022-12-22 21:14 UTC by Bantealem

- [x] In this pull request i have done the following
-  Can register a new user.
- User logs in with a combination of email and password.
- Hashed password should be stored in the database.
- Ask for confirmation of email.
- Can reset password.

2022-12-22 22:24 UTC, BenMukebo requested changes
### Hi @skyv26, @Bantealem,

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻

- No linter errors. ✔️ 
- Gitflow was correctly used.  ✔️   
- The application allows for registering a new user. 🥇
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_

``` ## Authors ```

- [ ] Update your Readme, This is a group project. Please let's include all the authors in the README file. This makes the README file professional and descriptive. 👨🏻‍🎨 

Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-22 22:24 UTC, BenMukebo commented on app/models/user.rb
> +# rubocop:disable all
- [ ] it is always a good practice to make sure you fix all linter errors instead of disabling them, A linter is great for identifying errors when you use standard rules. Remember, a linter analyzes your code for stylistic and programming errors against the rules it knows. 💯 😉

2022-12-22 22:24 UTC, BenMukebo commented on app/models/user.rb
> +  has_many :posts, foreign_key: :author_id
- [ ] The application should ask for an email confirmation. Let's add `confirmable` to your user.rb  models file:

```ruby
	devise :database_authenticatable, :registerable,
				:recoverable, :rememberable, :validatable, :confirmable
```

- [ ] And Make sure A user can reset the password in the application. 👍🏻

2022-12-22 22:24 UTC, BenMukebo commented on app/views/devise/registrations/edit.html.erb
> +    <%= f.label :email %><br />
- [ ] The views in devise for the registration and login must be modified to match the wireframes and your styling.
You can take a look at the wireframes in the [sneak peek](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/sneak_peek.md) of the project.

- Your Design:

![Screenshot from 2022-12-23 00-16-52](https://user-images.githubusercontent.com/79058364/209235088-b5b39a26-58a9-42b7-a864-48b637485e45.png)


- Original template:

![image](https://user-images.githubusercontent.com/79058364/208264719-cde14266-91f0-41af-9259-5993f6715d34.png)

2022-12-23 09:39 UTC, prolajumokeoni approved these changes
Hi @Bantealem 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- No linter errors ✅ 
- Git flow was used correctly 🚀 
- Good design 💯 
- Good Pr title and description 💪🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-23 10:20 UTC, merged