Add controllers
Bantealem/rails-blog-app pull request #5
Opened 2022-12-13 11:02 UTC by Bantealem

- [x] In this pull request I have made the following
- [x] I have setup the controllers and the view for each page

2022-12-13 11:50 UTC, Reem-lab requested changes
# Hi @Bantealem, 👋🏻👋🏻 

Good job so far! ✨💯🔥🔥
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media0.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights
- No Linters error ✅
- Followed GitFlow ✅
- Great working on the functionality for the controllers✅

## Required Changes ♻️
_Check the comments under the review._
- [ ] I think you didn't update your routes because it should follow the wireframe so please update it to put it inside resources. 🔥💯✨♻

you can add somthing like this:

>  resources :users, only: [:index, :show] do
 >  resources :posts, only: [:index, :show]
 > end


![image](https://user-images.githubusercontent.com/58553711/207310189-d013573f-4db9-436b-8850-d9fb75d694fb.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-13 12:45 UTC, FrederickMih requested changes
## Hi :raising_hand: @Bantealem, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.


![Screenshot from 2022-10-20 09-38-51](https://user-images.githubusercontent.com/63087491/207077883-42631f8a-22ae-40cf-a8d5-8fc39c197911.png)


## Highlights :green_circle: 


- PR is descriptive :+1: 
- All Linter checks passed :heavy_check_mark: 



 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-13 12:45 UTC, FrederickMih commented on config/routes.rb
> +  get "/users/:id/posts/:id/comments/:id/edit", to: "comments#edit"
- [ ] Based on the requirements of this project, you're not supposed to expose unnecessary routes. Please note that it is very important to always follow the requirements of any project given to you. We are learning to build our project step-by-step following strictly the requirements. You were supposed to have only two actions in your controller for now that's the #index and the #show actions hence we need only the routes for those two actions as seen below :+1: 

```ruby
resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show]
```

2022-12-14 06:35 UTC, Bantealem commented
Thank you for your constructive feedback

2022-12-14 07:37 UTC, prolajumokeoni requested changes
Hi @Bantealem 
Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Highlights
✔️ No linter errors
✔️ Git flow was correctly used 
✔️  Good PR title and Description

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-14 07:37 UTC, prolajumokeoni commented on config/routes.rb
>    resources :comments
- [ ] It would be better to nest these routes so that we can tell which user is trying to create or fetch posts, currently, you are missing an `end` keyword which is throwing an error, your routes should look like the example below ⬇️ 

 ```` 
resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show]
  end 
````

- [ ] Just as the previous reviewer requested, kindly delete the unnecessary routes, only the users and posts routes should be exposed

2022-12-14 08:02 UTC, prolajumokeoni approved these changes
Hi @Bantealem 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- No linter errors ✅ 
- Git flow was used correctly 🚀  
- Good Pr title and description 💪🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-14 08:14 UTC, merged